/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Orange LED -- GPIOD pin 13.
//	1 -- Led On
//	0 -- Led Off

int main(void) {
	char str[32];
	SystemInit();
	uartinit(9600);
	uartputs("Banana\r\n");
	uartputs("uart \r\n");
	//printf("1.RED LED ON\n2.RED LED OFF\n3.BLUE LED ON\n4.BLUE LED OFF\n ENTER CHOICE:");
	int choice;
	uartputs("1.RED LED ON\r\n2.RED LED OFF\r\n3.BLUE LED ON\r\n4.BLUE LED OFF\r\n ENTER CHOICE:\r\n");
	while(1){
	        uartgets(str);
		sscanf(str,"%d",&choice);
		
	switch(choice){
	case 1:
		SET_LED(RED);
		ON(RED);
	break;
	case 2:
		SET_LED(RED);
		OFF(RED);
	break;
	case 3:
		SET_LED(BLUE);
		ON(BLUE);
	break;
	case 4:
		SET_LED(BLUE);
		OFF(BLUE);
		break;
}}
	return 0;
}

